// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIGJ0h9jKJtD-xm3NeTnw6ww1Jxz3RrJM',
    appId: '1:910030302421:web:81cc95288fb54b6d11c65c',
    messagingSenderId: '910030302421',
    projectId: 'cloud-computing-2616f',
    authDomain: 'cloud-computing-2616f.firebaseapp.com',
    databaseURL: 'https://cloud-computing-2616f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cloud-computing-2616f.appspot.com',
    measurementId: 'G-F58LBBYVX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq-OaGbxsxxdAKee7jFTWgFAnAKG46byc',
    appId: '1:910030302421:android:0629b066fb176ec911c65c',
    messagingSenderId: '910030302421',
    projectId: 'cloud-computing-2616f',
    databaseURL: 'https://cloud-computing-2616f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cloud-computing-2616f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrxjxjaG2A06pnJQN3dPbJebCrkC-YE5M',
    appId: '1:910030302421:ios:3729136b3592e67211c65c',
    messagingSenderId: '910030302421',
    projectId: 'cloud-computing-2616f',
    databaseURL: 'https://cloud-computing-2616f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cloud-computing-2616f.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrxjxjaG2A06pnJQN3dPbJebCrkC-YE5M',
    appId: '1:910030302421:ios:3729136b3592e67211c65c',
    messagingSenderId: '910030302421',
    projectId: 'cloud-computing-2616f',
    databaseURL: 'https://cloud-computing-2616f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cloud-computing-2616f.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIGJ0h9jKJtD-xm3NeTnw6ww1Jxz3RrJM',
    appId: '1:910030302421:web:cb4279ef4034071b11c65c',
    messagingSenderId: '910030302421',
    projectId: 'cloud-computing-2616f',
    authDomain: 'cloud-computing-2616f.firebaseapp.com',
    databaseURL: 'https://cloud-computing-2616f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cloud-computing-2616f.appspot.com',
    measurementId: 'G-MYQL167CV5',
  );
}
